version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Restore solution
          command: dotnet restore 
      - run:
          name: Build solution
          command: dotnet build 
      - run:
          name: Run tests 
#           command: dotnet test --no-build --logger "trx;LogFileName=/root/project/UnitTestProject1/xunit-output.xml"
          command: dotnet test -c Debug "--logger:Console;verbosity=minimal" --diag:./bin/default/log.txt
      - store_artifacts:
          path: ./bin/default
          when: always
#       - store_artifacts:
#           path: /root/project/UnitTestProject1/xunit-output.xml

      # Convert xUnit output to JUnit output, as described at
      
      # http://geeks.akinox.com/2017/03/17/migrating-dotnetcore/#dotnet-test-and-shippable
  
 
