version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Restore solution
          command: dotnet restore 
      - run:
          name: Build solution
          command: dotnet build 
      - run:
          name: Run tests 
          command: dotnet test --no-build --logger "trx;LogFileName=/root/project/UnitTestProject1/TestResult/xunit-output.xml"
      - store_artifacts:
          path: /root/project/UnitTestProject1/TestResult/
          when: always
      - run:
          name: coverage
#           command: dotnet test --no-build -v n --results-directory:test_coverage --collect:"Code Coverage"
          command: dotnet test -c -v minimal 
            --no-build 
            --collect:"XPlat Code Coverage" 
            --results-directory './CodeCoverageResults'
      - store_artifacts:
          path: ./CodeCoverageResults

      # Convert xUnit output to JUnit output, as described at
      
      # http://geeks.akinox.com/2017/03/17/migrating-dotnetcore/#dotnet-test-and-shippable
  
 
